# Generated by Django 3.2.5 on 2022-09-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contributors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('school', models.CharField(max_length=100)),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('is_prof', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('LR', 'Lead Researcher'), ('SA', 'Student Assistant')], max_length=2)),
                ('articles', models.ManyToManyField(to='info_site.Article')),
            ],
        ),
    ]
